### PR TITLE
Merge gregdegruy:master into CatalystCode:master

### PR DESCRIPTION
**Pull request by gregdegruy**
Issues#75 🎈

### CODE REVIEW

**Comment by gregdegruy** [comment]
All done 😄 let me know if you want to meet about any of the changes.

**Comment by deadlyfingers** [comment]
@gregdegruy can you change your base from CatalystCode:master to ibex-version-1.0?

**Comment by morsh** [comment]
@deadlyfingers - I'll do it - You can click "Edit" than change the base for merge

**Comment by gregdegruy** [comment]
will review the conflict today and update

**Comment by morsh** [comment]
Migrated all changed to:
https://github.com/CatalystCode/ibex-dashboard/pull/119

**Pull request closed without merging**
