### PR TITLE
Fixed incorrect custom dimension property name for Goal event

### PR DESCRIPTION
**Pull request by garypretty**

### CODE REVIEW

**Comment by deadlyfingers** [comment]
This renaming update will be applied as part of the #293 issue.

**Comment by morsh** [comment]
Hi @garypretty - I'm assuming this is working well since you developed this template :)

**Comment by garypretty** [comment]
@morsh yes, I have tested. It was just with you saying you were initially merging to another branch to test. Anyway I have since tested on the v1 branch and it's all looking good.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by garypretty** [comment]
@deadlyfingers have the template changes you mentioned gone in now?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
